EXPERIMENT:
  NAME: ""
  TAG: "crld_ours,res34,res18"
  PROJECT: "imagenet_baselines"
  MIXED: true
  ALPHA: 0.2
  LOGIT_STAND: false

DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128

DISTILLER:
  TYPE: "CRLD_Ours"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [200, 300, 400]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crld_ours"


