EXPERIMENT:
  NAME: ""
  TAG: "reviewkd_ours,res34,res18"
  PROJECT: "imagenet_baselines"
  MIXED: true
  ALPHA: 0.2
  LOGIT_STAND: false
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 8
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "ReviewKD_Ours"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.05
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
REVIEWKD:
  CE_WEIGHT: 1.0
  REVIEWKD_WEIGHT: 1.0
  WARMUP_EPOCHS: 1
  SHAPES: [1,7,14,28,56]
  OUT_SHAPES: [1,7,14,28,56]
  IN_CHANNELS: [64,128,256,512,512]
  OUT_CHANNELS: [64,128,256,512,512]
  STU_PREACT: True
