EXPERIMENT:
  NAME: ""
  TAG: "MLLD_Ours,res32x4,shuv2"
  PROJECT: "cifar100_baselines_epoch960"
DISTILLER:
  TYPE: "MLLD_Ours"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 960
  LR: 0.01
  LR_DECAY_STAGES: [650, 800, 900]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "mlld_ours"
