EXPERIMENT:
  NAME: ""
  TAG: "MLLD_Ours,vgg13,vgg8"
  PROJECT: "cifar100_baselines"
  MIXED: false
  ALPHA: 0.8
  LOGIT_STAND: false
  BASE_WEIGHT: 2.0
DISTILLER:
  TYPE: "MLLD_Ours"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "mlld_ours"
